# This is a C project
language: c

# Generate two builds with both GCC and Clang
compiler:
  - gcc
  - clang

# Activate builds only for master
branches:
  only:
    - master

# Enable Docker
services:
  - docker


# Use Docker image containing my other repo Clog
before_install:
  - docker pull joh1/clog
  - docker run --detach --interactive --name clog joh1/clog

# Fetch the project from github inside the container
install:
  - docker exec clog git clone https://github.com/Moonstroke/CUTE.git cute


# Launch the tests from the container
script:
  - docker exec clog /bin/sh -c 'cd cute && make && make test'
