# This is a C project
language: c

# Generate two builds with both GCC and Clang
compiler:
  - gcc
  - clang

#Use a sudo-enabled environment
sudo: true


# Activate builds only for master
branches:
  only:
    - master


# Build and install dependencies
before_script:
  - sudo make installdeps

# Build the project and launch the tests
script:
  - make
  - make test
